// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import SmileOutlined from 'D:/Rohit ssd/Msspl/NodejsProject/attendanceweb/node_modules/@ant-design/icons/es/icons/SmileOutlined';
export default { SmileOutlined };
